var config = require('./config/config');
var express = require('./config/express');
var mongoose = require('./config/mongoose');
var db = mongoose();
var app = express();
var dbname = config.db;
var port = config.port;
var nodeEnv = process.env.NODE_ENV;
app.listen(port);
console.log(nodeEnv + ' server running at http://localhost:' + port);
console.log(nodeEnv + ' database connected at ' + dbname);
